### ISSUE TITLE
Delivery to the wrong place and Wrong list in groceries and inventory 

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#937] opened 2022-03-01 18:46 UTC
### Build number

476

### Bug description

The warehouse truck delivers pizza, salads and more to the XIII gift store, and the grocery and inventory of this store includes items from the fast food

### Savegame file

[32 [MConverter.eu] (1).txt](https://github.com/hovgaardgames/bigambitions/files/8164027/32.MConverter.eu.1.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/156229308-307d53fe-35a1-4c10-9428-9585fdc8e0fe.png)
![image](https://user-images.githubusercontent.com/98607052/156229480-336c9539-e60e-4b14-8631-3ee98933290b.png)

**Comment by Gerwanese** [comment] 2022-03-01 18:55
Probably duplicate of #899 

@Ckeptikya Did you follow the advice in the other bug?
> Will require you to remove and add again the destinations of the LogisticsManagers to fix it in your save

**Comment by Ckeptikya** [comment] 2022-03-01 18:56
Yes @Gerwanese

**Comment by Ckeptikya** [comment] 2022-03-01 19:11
No problems with other stores

**Comment by David-Goru** [comment] 2022-03-01 19:18
![imagen](https://user-images.githubusercontent.com/50799541/156234220-e10f1b95-1df5-4239-9d9c-eb069e4ced9f.png)
Pressing the remove button (red buttons with an X in them) from both destinations and re-adding them seems to work for me with your savegame.

**Closed by David-Goru** 2022-03-01 19:18 UTC
