### ISSUE TITLE
Delivery of furniture didn't work, because previous pallet but that's not true, problem with business overtake?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1329] opened 2022-09-10 15:44 UTC
### Build number

1152

### Bug description

Delivery of furniture didn't work, because previous pallet but that's not true, problem with business overtake?

I took over a business within an office building, wanted to deliver for the first time office supplies and had this message:

![afbeelding](https://user-images.githubusercontent.com/9866863/189490899-0441cc9c-cafc-4e55-a3e5-b773928f9add.png)

First time I delivered to that office building... so impossible there was a previous pallet. Maybe something going on with businesses you take over not registrating correctly for delivering furniture/appliances? I also sent my savegame for testing purposes if need, will contain the #github number.

David also tried and confirmed this as an issue.

**Comment by jokoho48** [comment] 2022-09-16 13:03
Fixed in Build 1253. this is caused by the position of the pallet colliding with Parked Vehicles, Pedestrians or Player Vehicles

**Closed by jokoho48** 2022-09-16 13:03 UTC
