### ISSUE TITLE
Bought car shown wrong in EconoView's "Last Transactions"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#218] opened 2021-06-19 23:40 UTC
Build 66

In "Last Transactions" in EconoView, there's just a placeholder shown instead of a car.

![grafik](https://user-images.githubusercontent.com/17579552/122657966-72566280-d168-11eb-9de8-8ad21fe6d812.png)

**Comment by David-Goru** [comment] 2021-11-11 10:07
Duplicate of #426

**Closed by David-Goru** 2021-11-11 10:07 UTC
Labels: confirmed
