### ISSUE TITLE
Cant Select Bizman Button when directly infront of Residential 

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#132] opened 2021-06-04 16:23 UTC
Alpha 4 - Build 51

When stood directly in front of the residential building you cant select the "Open In Bizman" Button.

https://user-images.githubusercontent.com/44293115/120833206-6d36c800-c559-11eb-9bf0-3ee83714054f.mp4

**Comment by adameg2305** [comment] 2021-06-04 16:27
Affected Buildings:
17th Third Street
21rd Third Street
25th Third Street
16th Fourth Avenue (When hovering over form the 3rd Street Side)
34th Third Street (Flashing menu)
30th Third Street
28th Third Street
26th Third Street 
(Pretty much every building)
Stay Tuned for more...

**Comment by Gerwanese** [comment] 2021-06-04 20:21
I wasn't able to reproduce this, however for me the dialog appears a little bit higher and that seems to be the reason because when turning the camera angle so that the button was "over" the player, it wouldn't be clickable in that area (just disappear). So there seems to be some issue with overlays and positioning, although hard to really catch it. Maybe moving the anchor point of the dialog a bit further back so it appears higher on the building could help.
![grafik](https://user-images.githubusercontent.com/17579552/120858134-9fa8eb00-c582-11eb-96be-f9fcdae9775c.png)

**Comment by Gerwanese** [comment] 2021-06-04 20:57
Couldn't reproduce for 17 Third Street but for 21 Third Street.
The difference for me on number 17 is that the dialog for me is slightly higher (two stairs below, instead of just one stair fully visible in Adam's video) - those positioning obviously is slightly different on different devices.
So when the dialog is too low, it will turn off once the cursor gets close to the player.
I thus think it's somewhat related to or even the same issue as #130 and caused by the automatic hiding of the dialog and building outline once the cursor is close to the player.

**Comment by David-Goru** [comment] 2022-06-10 09:03
Fixed in the past

**Closed by David-Goru** 2022-06-10 09:03 UTC
Labels: confirmed, low-priority
