### ISSUE TITLE
Typo in MyEmployees

### ISSUE THREAD

**Issue by Slickdrac** [hovgaardgames/bigambitions#852] opened 2022-02-13 14:42 UTC
### Build number

350

### Bug description

Under Exhaustion on the employee card in the MyEmployees menu, the last line says "Exhausted Employees deliver below **_they_** skill level". It should be "below **_their_** skill level.

### Screenshots or videos

![image](https://user-images.githubusercontent.com/10053421/153758353-5dbbf033-3330-45fd-a530-c775d2a13ef4.png)

**Comment by jokoho48** [comment] 2022-02-13 14:43
duplicate of https://github.com/hovgaardgames/bigambitions/issues/804

**Closed by jokoho48** 2022-02-13 14:43 UTC
