### ISSUE TITLE
Bizman purchase/rent interace does not show players current balance

### ISSUE THREAD

**Issue by Navsigda** [hovgaardgames/bigambitions#696] opened 2021-12-07 21:58 UTC
### Build number

245

### Bug description

During the initial starting steps of the game, the character is advised to rent 17 3rd Street. Right-clicking the building and opening the Bizman interface shows the deposit amount and daily rent, but doesn't indicate the players' current balance. 

### Steps to reproduce the bug

Right-clicking the building and opening the Bizman interface on 17 3rd Street.

### Screenshots or videos

![No current balance](https://user-images.githubusercontent.com/55465313/145112438-9bd0f2c0-49b3-45c6-a7ec-39e61ed0a676.png)

**Comment by Gerwanese** [comment] 2021-12-13 22:52
Closing this as it's not a bug but a feature suggestion. Feature suggestions should be posted in the community forums, as Github is used to manage bugs only.

**Closed by Gerwanese** 2021-12-13 22:52 UTC
