### ISSUE TITLE
Settings And Marking Buttons offset from actual text

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#808] opened 2022-01-24 22:32 UTC
### Build number

339

### Bug description

The Settings and Marketing buttons are offset from the text, unlike the other buttons.

### Savegame file

[Dodgy Buttons.txt](https://github.com/hovgaardgames/bigambitions/files/7929272/Dodgy.Buttons.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/44293115/150876001-c3fbc6a7-a13d-45b9-9f97-5b323f7083d6.mp4

**Comment by Gerwanese** [comment] 2022-01-24 22:58
I can't reproduce this. For me they work all normal.

**Comment by David-Goru** [comment] 2022-01-28 12:10
Can't reproduce it either, tested it on a 2560x1440 resolution. When pressing settings in your video, an error appears. Maybe is related to that

**Comment by David-Goru** [comment] 2022-07-19 14:03
Closing as can't reproduce it

**Closed by David-Goru** 2022-07-19 14:03 UTC
Labels: cannot-reproduce
