### ISSUE TITLE
Pedestrians stop whenever the player clicks "Interview" but whilst the player is running to the pedestrian clicks "WASD"

### ISSUE THREAD

**Issue by Ampire-M** [hovgaardgames/bigambitions#774] opened 2022-01-21 06:37 UTC
### Build number

332

### Bug description

Pedestrians stop whenever the player clicks "Interview" but whilst the player is running to the pedestrian clicks "WASD"

### Steps to reproduce the bug

1. Hover with mouse the pedestrian
2. Click "Interview"
2. During player movement to pedestrian press "W"/"A"/"S"/"D"

**Expected result:** Pedestrians proceeds his journey
**Actual result:** Pedestrian stops until user clicked anywhere/or walk to pedestrian

**Comment by David-Goru** [comment] 2022-01-21 08:37
That's intended! So you can interview them, making it easier to click the interview button. :)

**Comment by Ampire-M** [comment] 2022-01-21 09:06
Oh, ok. But, what about the fact that they don't proceed to walk after hover is removed?

**Comment by David-Goru** [comment] 2022-01-21 09:18
That would be a bug, yes! I can't seem to reproduce it, though. If you find the steps to get that bug, comment them here and we'll check it!

**Comment by Ampire-M** [comment] 2022-01-21 17:25
I finally got to my PC, and reproduced it, updated the steps.

**Comment by David-Goru** [comment] 2022-04-26 10:48
Beta 2 removes interviews. Closing this

**Closed by David-Goru** 2022-04-26 10:48 UTC
Labels: confirmed
