### ISSUE TITLE
BizMan blurry and follow-up issues

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#356] opened 2021-07-28 22:11 UTC
Alpha 5 - Build 106

The game was running perfectly fine until running down to the metro wholesale (2x speed) then opened bizman by clicking the "open in bizman" button on the building menu. After trying to close the menu it goes incredibly slowly, looks to be 1 frame every couple of seconds, and the background blur persists during the rest of the game. the screen then fixes itself when you go inside any building, but as soon as you try to open any menu it wont open, or it will be very slow.
![Ra8tC1](https://user-images.githubusercontent.com/44293115/127402603-034894aa-6754-417a-b28a-1f4e83545586.jpg)

https://user-images.githubusercontent.com/44293115/127402805-4e5fcbe6-8f92-4359-b305-cc52ec73f07d.mp4

**Comment by adameg2305** [comment] 2021-07-28 22:12
Save Game
[106blur.txt](https://github.com/hovgaardgames/bigambitions-public/files/6896729/106blur.txt)

**Comment by Gerwanese** [comment] 2021-07-28 23:04
I couldn't reproduce the exact issue, but can confirm sporadic performance issues. For me it was while walking on the sidewalk (normal speed) suddenly it started shuddering with about one frame per second. After opening and closing Voogle Maps everything went back to normal for me.

Adding the Player.log just in case there might be something relevant:
[Player.log](https://github.com/hovgaardgames/bigambitions-public/files/6896913/Player.log)

**Comment by Albrat32** [comment] 2021-07-31 09:22
I just triggered this bug by walking to the bank while it was closed.  clicked the Bizman and then press ESC.  The screen stays blurry and the UI of everything you do stays up. I returned to main menu then loaded game again and it sorted itself. (did not exit game.)

**Comment by Gerwanese** [comment] 2021-07-31 18:27
If it happens to any of you again, could you attach the Player.log which can be found in the same directory as the savegames?
Maybe we can find some error in there.

**Comment by adameg2305** [comment] 2021-07-31 18:35
> 
> 
> If it happens to any of you again, could you attach the Player.log which can be found in the same directory as the savegames?
> Maybe we can find some error in there.

Sure thing

**Comment by Gerwanese** [comment] 2021-08-05 20:34
Now I got the same issue, happened to me shortly after experiencing bug #436.
Updated Player.log (too large to attach unzipped):
[Player.zip](https://github.com/hovgaardgames/bigambitions-public/files/6941538/Player.zip)

**Comment by jokoho48** [comment] 2022-07-21 14:57
Fixed a while ago

**Closed by jokoho48** 2022-07-21 14:57 UTC
Labels: confirmed
