### ISSUE TITLE
is no "Interview" button

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#873] opened 2022-02-25 20:36 UTC
### Build number

469

### Bug description

is no "Interview" button (the task is to conduct an interview). ещё  npc hovered

### Steps to reproduce the bug

try to poll the population
I noticed that NPCs get stuck at this building under the wing

### Savegame file

[Uploading 3 [MConverter.eu].txt…]()

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/155799316-723b457e-2067-4e18-8b1e-cea26e76edbf.png)

**Comment by Gerwanese** [comment] 2022-02-25 21:40
Duplicate of #866

**Closed by Gerwanese** 2022-02-25 21:40 UTC
