### ISSUE TITLE
Car Stuck on Side

### ISSUE THREAD

**Issue by Snyper1010** [hovgaardgames/bigambitions#982] opened 2022-03-24 11:37 UTC
### Build number

488

### Bug description

My car has flipped on to its side (my own error), unfortunately it is now stuck on its side and I am getting parking tickets as it is deemed to be illegally parked.

### Steps to reproduce the bug

Drive car at full speed and perform a tight turn so that the car turns on to its side. The car will now be stuck.

### Savegame file

[New Shaun Save Game.txt](https://github.com/hovgaardgames/bigambitions/files/8341070/New.Shaun.Save.Game.txt)

### Screenshots or videos

![Screenshot 2022-03-24 112538](https://user-images.githubusercontent.com/67522485/159908285-953d54e9-c2e8-48a4-9e7a-ad9d62582e28.png)

**Comment by Gerwanese** [comment] 2022-03-24 12:10
Duplicate of #966, should get fixed in Beta 1.
For now the only way to fix it is buying a new car and trying to push this car back on its wheels (not guaranteed to work though).

**Closed by Gerwanese** 2022-03-24 12:10 UTC
Labels: duplicate
