### ISSUE TITLE
Graphic bugs at enhanced street area

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#118] opened 2021-06-01 01:39 UTC
At the enhanced street area (with cracks, steam etc.) you can see a line near the road crossing where the surface color looks different (more or less visible during different times of the day).
During sunset, all cars in the area also look very "frosty" as if they would be covered with ice.
Exactly at 9pm there's a sudden lighting change (happens every day exactly at that time). After that, the streets look "normal" again with no visible bugs.

https://user-images.githubusercontent.com/17579552/120254730-c917fd00-c28a-11eb-8772-eb14179b90bd.mp4

https://user-images.githubusercontent.com/17579552/120254811-f369ba80-c28a-11eb-90c2-9c14442e05e8.mp4

**Comment by jhovgaard** [comment] 2021-06-01 07:15
Caused by road prefabs using new and old road shader. Will be fixed once the new shader has been implemented for all road prefabs.

**Comment by jokoho48** [comment] 2022-07-21 14:53
fixed along time ago

**Closed by jokoho48** 2022-07-21 14:53 UTC
Labels: confirmed, currently-not-fixable
