### ISSUE TITLE
Zombie Cars between 6th Str / 8th Str / 1st Ave / 2nd Ave

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#825] opened 2022-01-29 17:37 UTC
### Build number

340

### Bug description

In the block between 6th and 8th Street / 1st and 2nd Avenue there are zombie cars getting spawned offroad and disappearing again.

### Savegame file

[Build340-ZombieCarsAreComingForUs.json.txt](https://github.com/hovgaardgames/bigambitions/files/7964229/Build340-ZombieCarsAreComingForUs.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/151671295-13b84a9d-c4c1-48d9-a9f7-0a4d635f19fb.mp4

![grafik](https://user-images.githubusercontent.com/17579552/151671301-686db145-89c4-47c0-a8e2-9c4a87bd2584.png)

**Comment by jhovgaard** [comment] 2022-02-08 09:02
This is caused by traffic preparations for Midtown. Should not be worked on, as it resolves itself once Midtown is done.

Keeping this open to avoid duplicates.

**Comment by jhovgaard** [comment] 2022-05-03 11:50
Fixed in build 730

**Closed by jhovgaard** 2022-05-03 11:50 UTC
Labels: confirmed, low-priority
