### ISSUE TITLE
Massive FPS drop when speeding up your shift

### ISSUE THREAD

**Issue by Libror** [hovgaardgames/bigambitions#672] opened 2021-11-06 11:51 UTC
### Build number

245

### Bug description

![GIF 06 11 2021 12-51-07](https://user-images.githubusercontent.com/47794032/140608563-cb65b943-dcd2-497d-8acb-92cdfedbd7cd.gif)

**Comment by Libror** [comment] 2021-11-06 12:13
After tabbing out of the game whilst it was on fast forward mode and around 5 customers entered my store, it dropped down to 4fps

**Comment by Gerwanese** [comment] 2021-12-13 23:04
I would call this expected behaviour, as a lot more calculations have to be done within the same time when using fast-forward. @jhovgaard What do you think? Bug or no bug?

**Comment by jhovgaard** [comment] 2021-12-14 08:10
It might be the gif, but it looks like the machine is already struggling with fps even when not fast-forwarding. We might want to consider disabling fast-forward (but still have time machine available), if we can detect the CPU/GPU is below minimum specs.

@Libror can you confirm what CPU and GPU you got?

**Comment by Libror** [comment] 2021-12-15 16:07
@jhovgaard The gif is really laggy. Rendered it at about 10fps. However the normal gameplay runs at a smooth 144fps.

Specs:
Intel i7-6700k
16GB Ram
GTX 980 TI at 1920x1080
Also playing this game on an SSD

**Comment by jhovgaard** [comment] 2021-12-15 21:39
Alright then we definitely need to find a solution. Thanks for the info @Libror

**Comment by jokoho48** [comment] 2021-12-27 17:41
Fixed in Build 297.

**Closed by jokoho48** 2021-12-27 17:41 UTC
