### ISSUE TITLE
Navigating to an unreachable destination

### ISSUE THREAD

**Issue by Navsigda** [hovgaardgames/bigambitions#693] opened 2021-12-07 21:36 UTC
### Build number

245

### Bug description

The interior of a clipped building is interactable, allowing the mouse cursor to be placed inside the building and clicked, causing the character to go into an infinite loop of walking against the building to a destination it can never reach. 

### Steps to reproduce the bug

Rotating the camera to an angle where the building textures clip from the frame and clicking any black space inside it.

### Screenshots or videos

![Navigating to an unreachable destination](https://user-images.githubusercontent.com/55465313/145109680-361e8c81-8866-4a4c-bf4b-a9c2404858a1.png)

**Comment by Gerwanese** [comment] 2021-12-13 23:02
Duplicate of #98, additionally combined with #695 making it even worse for this specific building. Closing as duplicate.

**Closed by Gerwanese** 2021-12-13 23:02 UTC
