### ISSUE TITLE
Save/settings dialog box appears underneath building information in Voogle Maps

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#930] opened 2022-03-01 05:31 UTC
### Build number

474

### Bug description

In Voogle Maps, if you click on a building to bring up its address/building type dialog box and then click the save/quit to desktop button in the top-right corner, the Voogle Maps dialog box remains on top, needing to be dismissed before being allowed to access the save/quit buttons if the building you clicked on was towards the center of the screen

If you bring up the save menu first, you can't click on anything else in the game, so I'd expect the save menu to have priority over the Voogle Maps dialog box

### Steps to reproduce the bug

- Open Voogle Maps
- Click on a building towards the center of your screen
- Click the gear in the top-right to open the save/quit menu

### Savegame file

[sameron_474_save_dialog.txt](https://github.com/hovgaardgames/bigambitions/files/8158978/sameron_474_save_dialog.txt)

### Screenshots or videos

![20220301182503_1](https://user-images.githubusercontent.com/99119499/156110764-a3dcc1c5-0b7e-40e7-902c-52ae2a6abe06.jpg)

**Comment by Gerwanese** [comment] 2022-03-01 09:18
Duplicate of #789

**Closed by Gerwanese** 2022-03-01 09:18 UTC
