### ISSUE TITLE
Can't enter car if parked incorrectly

### ISSUE THREAD

**Issue by CoolGingerGinger** [hovgaardgames/bigambitions#419] opened 2021-08-04 00:44 UTC
Alpha 5 (Build 132)
I was in the drive through wholesale store and parked too close to the check-out counter. This made it so I could not get back into my car.

Additionally, I can take items out of the car, but am unable to put them back in after paying for them. 

![Bug Report (2)](https://user-images.githubusercontent.com/88410729/128103254-25c04671-1f45-464d-9d6f-8d8b4ca75dad.png)

Saving and re-loading save fixes the issue and allows me to get into the car. But problem is reproducible.

**Comment by Gerwanese** [comment] 2021-08-04 16:21
Confirmed. It only happens in a very special situation - when just the moment you leave the car it makes a little "jump". Otherwise (and also after reloading) you will just "beam" into the car from besides the cash register.
Savegame attached to demonstrate the situation, although after loading the problem is gone.

[Build132-CarClosed.txt](https://github.com/hovgaardgames/bigambitions-public/files/6932791/Build132-CarClosed.txt)

**Comment by Gerwanese** [comment] 2021-08-06 11:58
Related to #193

**Comment by Gerwanese** [comment] 2022-04-18 18:42
There's still an issue with entering the car in certain positions, see https://community.bigambitionsgame.com/t/unable-to-enter-illegally-parked-car/1103

**Comment by jokoho48** [comment] 2022-04-19 12:49
cant reproduce needs save game.

**Comment by jokoho48** [comment] 2022-04-20 10:10
Fixed in Build 718.

**Closed by jokoho48** 2022-04-20 10:10 UTC
Labels: confirmed
