### ISSUE TITLE
Tutorial not explaining concept of whoesales stores

### ISSUE THREAD

**Issue by damianshiell** [hovgaardgames/bigambitions#380] opened 2021-07-30 22:28 UTC
not able to put purchased gifts into new gift business metal shelf

**Comment by Gerwanese** [comment] 2021-07-30 23:13
@damianshiell Can you explain in detail how you're trying it? Ideally with screenshots or video?

After buying a box of gifts at the wholesales store, you have to hold the box in hands and then left click the metal shelf. Then the box should disappear and the metal shelf should contain 200 gifts.

**Comment by damianshiell** [comment] 2021-07-31 07:41
Hi I will do, I was buying multiple ones, they then went into a paper bag
which I couldn't remove them from.  Will update with some pics when I get
back online 😁

Damian

**Comment by damianshiell** [comment] 2021-07-31 07:42
Also, I bought them from the gift shop rather than the wholesale store
which could be the problem

Damian

**Comment by Gerwanese** [comment] 2021-07-31 11:00
Alright, that's the problem there. From the gift shop you only get things for "personal use" but not to place them in your shop. To fill up your own shop, you always have to buy from the wholesales store (the "normal" one or the or drive-in wholesales).

It's not a bug but since a lot of players already ran into the issue, it shows the current tutorial not being good for new players. Will be addressed in a future update.

**Comment by damianshiell** [comment] 2021-07-31 11:43
awesome - you're ahead of me there :)
Also need to potentially rearrange the order of the basic training otherwise you can;t place the mop

Many thanks for the speedy response and great work guys!

I put in feedback earlier - but a wsad component for moving the character would be really helpful as sometimes really awkward to move chappy around :)

Damian

**Comment by Gerwanese** [comment] 2021-07-31 17:48
Thanks for the feedback!
We have to keep this issue open though, otherwise Jonas might forget fixing the tutorial. :)

**Comment by damianshiell** [comment] 2021-08-01 18:28
Nice :)

Sorry - first time alpha testing - learning the ropes myself for my own
projects.  Currently within a GameDev.TV course covering all the basics.

Consultant during the day, wannabe game developer during the twilight hours
:)

Damian

**Comment by jhovgaard** [comment] 2021-08-08 15:24
Hi guys,

I'm bumping this to alpha 7 where the help system will be introduced. We need more UI space to describe this.

**Comment by damianshiell** [comment] 2021-08-09 11:40
thank you - sorry - been whumped at work doing some automation within Logic
Apps/Pipelines/RestAPIs and SQL Servers :)

Will be able to look do some more over the next few days.

Damian

**Closed** 2022-07-21 15:01 UTC
Labels: confirmed
