### ISSUE TITLE
Unpaid Balance goes over 2 lines if too expensive

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#782] opened 2022-01-22 11:56 UTC
### Build number

337

### Bug description

If you add lots of expensive items to the hand truck and the price goes above 7 characters it will then split the text over 2 lines

### Screenshots or videos

![NVIDIA_Share_cRFxMnj6r4](https://user-images.githubusercontent.com/44293115/150637567-3ce292e4-0786-43c1-be1c-8796f9c42880.png)

**Comment by Gerwanese** [comment] 2022-01-22 13:24
Confirmed. Happens with the pizza oven because it has a decimal part, but would probably happen as well if you ever manage to get more than 100,000 onto the hand truck.

[Build337-DoubleLined.json.txt](https://github.com/hovgaardgames/bigambitions/files/7918394/Build337-DoubleLined.json.txt)

**Comment by David-Goru** [comment] 2022-02-23 08:49
Fixed in build 465

**Closed by David-Goru** 2022-02-23 08:49 UTC
Labels: confirmed
