### ISSUE TITLE
Possible to get stuck in a register where you have an employee already assigned

### ISSUE THREAD

**Issue by ChrisB-M** [hovgaardgames/bigambitions#30] opened 2021-04-26 09:18 UTC
In the early stage of the game, I hired an employee before "running my store for 2 days" as per Fred's instructions

When I clicked on the register to take over from George, it says George is currently assigned but subsequently does not allow me any further movement and I am locked into that screen forever.

![Stuck](https://user-images.githubusercontent.com/6843892/116059411-b6514d80-a678-11eb-9470-1300b0f59d4e.PNG)

![Stuck 2](https://user-images.githubusercontent.com/6843892/116059487-ccf7a480-a678-11eb-9baf-c9cf72ab3c87.PNG)

**Comment by ChrisB-M** [comment] 2021-04-26 09:59
Update: removing the employee from the shift does not fix the issue

**Comment by Gerwanese** [comment] 2021-04-26 19:26
I'm unable to reproduce this, the Cancel button is always there.
![grafik](https://user-images.githubusercontent.com/17579552/116138902-b2074d80-a6d5-11eb-8b93-48c8224848ea.png)
Did you play with the latest version of the game (update came late Saturday night on Steam; currently there's even a newer version of today)?

**Comment by Gerwanese** [comment] 2021-04-26 19:56
Do you have a savegame of right before this happens (obviously you couldn't save anymore afterwards)?
Savegames are in Windows located at:

> C:\Users\USERNAME\AppData\LocalLow\Hovgaard Games\Big Ambitions

Replace "USERNAME" with your username. The AppData folder is invisible, so you either have to enter it manually or change display settings to show hidden files and folders.
In the folder you'll find a .json file for each savegame. Additionally there are a Player.log and a Player-prev.log which might be useful as well.

**Comment by ChrisB-M** [comment] 2021-04-27 06:57
I can reproduce the bug by assigning and un-assigning shifts without leaving the store.

I attach the save files from a day earlier (SallahTwo) and the file from imminently before bug appears


[Cashier Bug.zip](https://github.com/hovgaardgames/bigambitions-public/files/6382518/Cashier.Bug.zip)

![cashier bug test](https://user-images.githubusercontent.com/6843892/116198613-12c27480-a72e-11eb-9f94-858a1e3a9f2d.PNG)

**Comment by Gerwanese** [comment] 2021-04-27 17:10
I'm not able to reproduce this with your savegame, I also tried unassigning and reassigning shifts.
![grafik](https://user-images.githubusercontent.com/17579552/116282737-6b742a80-a78b-11eb-813a-360a4e154963.png)
There must be something else to it.

In your logfile I found a few errors which I also get, but two errors that don't exist in my logfile:
```
InvalidOperationException: Sequence contains more than one matching element
  at System.Linq.Enumerable.SingleOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00077] in <55b3683038794c198a24e8a1362bfc61>:0 
  at BuildingManager.SetWorkingState () [0x000ca] in <58b5fc8998c0443da0b0ea7018579f05>:0 
  at BuildingManager.Start () [0x0027c] in <58b5fc8998c0443da0b0ea7018579f05>:0 
```

```
<color=#0099bc><b>DOTWEEN ► </b></color>Target or field is missing/null () ► 

  at (wrapper managed-to-native) UnityEngine.CanvasGroup.set_alpha(UnityEngine.CanvasGroup,single)
  at DG.Tweening.DOTweenModuleUI+<>c__DisplayClass0_0.<DOFade>b__1 (System.Single x) [0x00000] in <30ce2bf8dcb74eeb921025b57f4dbf62>:0 
  at DG.Tweening.Plugins.FloatPlugin.EvaluateAndApply (DG.Tweening.Plugins.Options.FloatOptions options, DG.Tweening.Tween t, System.Boolean isRelative, DG.Tweening.Core.DOGetter`1[T] getter, DG.Tweening.Core.DOSetter`1[T] setter, System.Single elapsed, System.Single startValue, System.Single changeValue, System.Single duration, System.Boolean usingInversePosition, DG.Tweening.Core.Enums.UpdateNotice updateNotice) [0x000e3] in <2348fb5ecc9e4e689f37f7d7fadaea9a>:0 
  at DG.Tweening.Core.TweenerCore`3[T1,T2,TPlugOptions].ApplyTween (System.Single prevPosition, System.Int32 prevCompletedLoops, System.Int32 newCompletedSteps, System.Boolean useInversePosition, DG.Tweening.Core.Enums.UpdateMode updateMode, DG.Tweening.Core.Enums.UpdateNotice updateNotice) [0x00034] in <2348fb5ecc9e4e689f37f7d7fadaea9a>:0 
```

**Comment by Gerwanese** [comment] 2021-04-27 17:11
Just an idea: Maybe you can try to click in the area where the Cancel button should be, just to see if it's actually there and just invisible.

**Comment by David-Goru** [comment] 2022-01-28 11:37
Fixed in the past

**Closed by David-Goru** 2022-01-28 11:37 UTC
Labels: cannot-reproduce
